version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  frontend:
    working_dir: /app
    image: node:18
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
